[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"

#solc = "0.8.15"
optimizer = true
optimizer_runs = 200

rpc_endpoints = { mainnet = "https://eth-mainnet.g.alchemy.com/v2/qWXgfSwND6X1hX9FjENsPqdyM0TfQJx2",  bsc = "https://rpc.ankr.com/bsc", bscTest = "https://bsc-testnet.nodereal.io/v1/73509119cb1c426cb38a01cecfce296d", testnet = "http://18.246.17.16:8515" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
