[profile.default]
src = "src"
out = "out"
libs = ["lib"]

#solc = "0.8.15"
optimizer = true
optimizer_runs = 200

rpc_endpoints = { mainnet = "https://rpc.ankr.com/eth",  bsc = "https://rpc.ankr.com/bsc", bscTest = "https://bsc-testnet.nodereal.io/v1/73509119cb1c426cb38a01cecfce296d" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
